version: '3.6'

services:

#================================================================================================
# RBENV (Ruby Environment)
#================================================================================================
  rbenv:
    restart: unless-stopped
    container_name: rbenv_${UBUNTU_VERSION:-18.04}_${RUBY_VERSION:-2.7.1}
    build:
      context: .
      args:
        - UBUNTU_VERSION=${UBUNTU_VERSION:-18.04}
        - RUBY_VERSION=${RUBY_VERSION:-2.7.1}
    ports:
      - "${RBENV_PORT:-325}:22"
    tty: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
